### PR TITLE
Moved `tests` to `tests/miniconda`

### PR DESCRIPTION
**Pull request by jiawen**
Related: #24.

### CODE REVIEW

**Comment by jiawen** [comment]
Not sure what happened with the tests - it's complaining that the `WORKSPACE` file is missing?

**Comment by GabrielDougherty** [comment]
Change the path:

https://github.com/spietras/rules_conda/blob/9f85c13da012f0c01ed605b369ca54a1bb29f271/tests/miniconda/WORKSPACE#L28

to `path = "../../"`

**Comment by jiawen** [comment]
> Change the path:
> 
> https://github.com/spietras/rules_conda/blob/9f85c13da012f0c01ed605b369ca54a1bb29f271/tests/miniconda/WORKSPACE#L28
> 
> to `path = "../../"`

Oops. Yeah, I discovered this myself when running `bazel test` locally. Should have checked my mail first.

**Review by spietras — APPROVED** [review]
Great, I'm merging this one right away

**Pull request merged**
